### ISSUE TITLE
Open Test 

### ISSUE THREAD

**Issue by Salem-Abderaouf** [Salem-Abderaouf/weecho#3]
I need an open test of Fast Forward section which has a body and phone number input 
I will use set method of firebase 
```
const userID = db.auth().currentUser.uid

db.database().ref('u\${userID}\fastmsg')```

**Comment by Salem-Abderaouf** [comment]
@Aissaoui-Ahmed  I need test for this object from firebase 
```
fastmsg : {
      content:'User Message goes here',
      phoneNUmebr: xxxxxxxxxx,
}

**Comment by Aissaoui-Ahmed** [comment]
> @Aissaoui-Ahmed I need test for this object from firebase
> 
> ```
> fastmsg : {
>       content:'User Message goes here',
>       phoneNUmebr: xxxxxxxxxx,
> }
> ```

Done!

**Comment by Aissaoui-Ahmed** [comment]
@Salem-Abderaouf try create new user!
